# Generated by Django 5.2.9 on 2026-01-04 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('cnn_prediction', models.CharField(max_length=20)),
                ('cnn_confidence', models.FloatField()),
                ('cnn_gradcam', models.ImageField(blank=True, null=True, upload_to='gradcam/%Y/%m/%d/')),
                ('resnet_prediction', models.CharField(max_length=20)),
                ('resnet_confidence', models.FloatField()),
                ('resnet_gradcam', models.ImageField(blank=True, null=True, upload_to='gradcam/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_processing_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comparison Result',
                'verbose_name_plural': 'Comparison Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('model_used', models.CharField(choices=[('custom_cnn', 'Custom CNN'), ('resnet50', 'ResNet-50')], max_length=20)),
                ('predicted_class', models.CharField(choices=[('normal', 'Normal'), ('pneumonia', 'Pneumonia')], max_length=20)),
                ('confidence', models.FloatField()),
                ('gradcam_image', models.ImageField(blank=True, null=True, upload_to='gradcam/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
