# Generated by Django 5.2.4 on 2026-01-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_alter_comparisonresult_cnn_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonresult',
            name='resnet_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonresult',
            name='resnet_prediction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
